//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuseCP.Portal {
    
    
    public partial class UserAccountAppearanceSettings {
        
        /// <summary>
        /// lnkAppearanceBranding control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkAppearanceBranding;
        
        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnCancel;
    }
}
