// Copyright (C) 2025 FuseCP
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

﻿using System.Xml.Serialization;
using System;
namespace FuseCP.Providers.WebAppGallery
{
    [Flags]
    public enum DeploymentParameterValidationKind
    {
        None = 0,
        AllowEmpty = 1,
        RegularExpression = 2,
        Enumeration = 4,
        Boolean = 8,
    }

    [Flags]
    public enum DeploymentParameterWellKnownTag : long
    {
        None = 0L,
        
        AppHostConfig = 1L,
        AppPoolConfig = 2L,
        Boolean = 4L,
        ComObject32 = 8L,
        ComObject64 = 16L,
        DBAdminPassword = 32L,
        DBAdminUserName = 64L,
        DBConnectionString = 128L,
        DBName = 256L,
        DBServer = 512L,
        DBUserName = 1024L,
        DBUserPassword = 2048L,
        FlatFile = 4096L,
        Hidden = 8192L,
        IisApp = 16384L,
        MetaKey = 32768L,
        MySql = 65536L,
        MySqlConnectionString = 131072L,
        New = 262144L,
        RegKey = 524288L,
        SetAcl = 1048576L,
        Sql = 2097152L,
        SqLite = 4194304L,
        SqlConnectionString = 8388608L,
        Password = 16777216L,
        PhysicalPath = 33554432L,
        VistaDB = 67108864L,
        Validate = 134217728L,
        SqLiteConnectionString = 268435456L,
        SqlCE = 536870912L,
        NoStore = 1073741824L,
        AppURL = 2147483648L,
        NoProtocol = 4294967296L,
        DBUserConnectionString = 8589934592L,
        DBAdminConnectionString = 17179869184L,
        WebPIApplicationID = 34359738368L,
        Ignore = 68719476736L,
        AutoGenerated = 137438953472L,
        SingleLineConnectionString = 274877906944L,
        //SiteUserPassword = 549755813888,


        AllKnown = 
            AppHostConfig | 
            AppPoolConfig | 
            Boolean | 
            ComObject32 | 
            ComObject64 |
            DBAdminPassword |
            DBAdminUserName |
            DBConnectionString |
            DBName |
            DBServer |
            DBUserName |
            DBUserPassword |
            FlatFile |
            Hidden |
            IisApp |
            MetaKey |
            MySql |
            MySqlConnectionString |
            New |
            RegKey |
            SetAcl |
            Sql |
            SqLite |
            SqlConnectionString |
            Password |
            PhysicalPath |
            VistaDB |
            Validate |
            SqLiteConnectionString |
            SqlCE |
            NoStore |
            AppURL |
            NoProtocol |
            DBUserConnectionString |
            DBAdminConnectionString |
            WebPIApplicationID |
            Ignore |
            AutoGenerated |
            SingleLineConnectionString 
    }

	[Serializable]
    public class DeploymentParameter
    {
        #region Constants
        public const string ResourceGroupParameterName = "FCPResourceGroup";
        #endregion

        #region Properties
        public string FriendlyName { get; set; }
		public string Name { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
		public string DefaultValue { get; set; }
        public DeploymentParameterValidationKind ValidationKind { get; set; }
        public string ValidationString { get; set; }
        public DeploymentParameterWellKnownTag WellKnownTags { get; set; }
        public string ValuePrefix { get; set; }
        public string ValueSuffix { get; set; }
        #endregion

#if DEBUG
        public override string ToString()
        {
            return String.Format("{0}=\"{1}\", Tags={2}", Name, Value, WellKnownTags);
        }
#endif

	    public void SetWellKnownTagsFromRawString(string rawTags)
	    {
	        string[] tags = rawTags.Split(new[] {','}, StringSplitOptions.RemoveEmptyEntries);
	        DeploymentParameterWellKnownTag wellKnownTags = DeploymentParameterWellKnownTag.None;
	        foreach (string tag in tags)
	        {
                try
                {
                    wellKnownTags |= (DeploymentParameterWellKnownTag)Enum.Parse(typeof(DeploymentParameterWellKnownTag), tag, true);
                }
                catch(Exception){ _ = 0; }
	        }

	        WellKnownTags = wellKnownTags & DeploymentParameterWellKnownTag.AllKnown;
	    }
    }
}
